### ISSUE TITLE
Ingest UI: Add single new metadata

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#689] opened 2022-03-04 08:48 UTC
**User story**
As a data submitter
I want the ability to add single metadata via the UI
so that I can add more info on my experiment data

**Acceptance Criteria**
Given I previously submitted data to DCP (donor - specimen - cell suspension - files)
When I add a new protocol and link it to an existing process
Then it will be submitted to DCP (i.e. links.json updated and new metadata file added to Terra staging area)

Please note that it is possible to add a set of metadata via a new submission but the set should contain an assay process. 

This is part of scenario 6 in Exporting Updates as documented in https://docs.google.com/document/u/2/d/1nTZDW9xQhgZfM6jQkBbK2O68CRvALPiJ8F-noiEvxTA/edit

### Small Issues:
- [x] Adding new metadata doesn't update table totals
    - Using the refresh button at the top of the page fixes this
    - As long as the staging manager allows the change (see below)
- [x] Missing word in `New type - concreteType has been **added** successfully `
- [x] Don't show protocol:  `type/protocol/x.x.x/protocol`

### Possibly Larger / for investigation
- [x] Update Submission status on Metadata change
    - Might already be working, Alegria is investigating.
- [x] Do the changes get sent to terra?
    - Linking definitely does.
    - What about new / edit / deleted metadata?
        - Is this ticket #695?
- [ ] Is the mandatory setting coming from the schema or somewhere else?

### Issues needing new tickets 
- Hide Add, Edit, Delete metadata options if submission is not in editable state: #730
    - Non-Editable States: Submitted, Processing, Archiving, Archived, Exporting
- Add Hide Save button option to metadata form, use in the details dialog #731
- Run javascript validation on form before clicking save (more than just mandatory fields) #732

**Comment by MightyAx** [comment] 2022-03-09 11:16
A thought (as a reminder to to discuss later): Do we need to be able to open new blank submissions if an open submission doesn't currently exist? (perhaps because all current submissions have already been submitted)

**Comment by aaclan-ebi** [comment] 2022-03-09 13:22
If the submission has already been submitted, we will "open" that submission and it should be submittable again.

**Comment by aaclan-ebi** [comment] 2022-03-15 13:45
script to add a metadata: https://github.com/ebi-ait/hca-ebi-dev-team/pull/474/files

**Comment by MightyAx** [comment] 2022-03-15 13:51
Tasks:

- [x] Broker: Get list of concrete_types per base type (building on: https://github.com/ebi-ait/ingest-broker/pull/38)

UI:

- [x] User clicks new biomaterial/protocol/process
- [x] UI asks which concrete type to use out of a list
- [x] UI displays "new metadata" form based on "edit metadata" form
- [x] post to core
- [x] link new meta to project in core

Consideration: Do we only add the latest version of the schema?

**Comment by aaclan-ebi** [comment] 2022-03-15 14:02
PR containing broker api endpoints to retrieve schema info: https://github.com/ebi-ait/ingest-broker/pull/38/files

**Comment by amnonkhen** [comment] 2022-03-18 09:41
PRs to be reviewed today.

**Comment by MightyAx** [comment] 2022-03-18 09:41
Ingest UI PR: https://github.com/ebi-ait/ingest-ui/pull/165

**Comment by ESapenaVentura** [comment] 2022-03-21 09:48
pending review

**Comment by gabsie** [comment] 2022-03-22 09:45
@yusra-haider will catch up with @MightyAx

**Comment by MightyAx** [comment] 2022-03-23 13:47
Going to work with @ESapenaVentura on User Testing.

**Comment by ESapenaVentura** [comment] 2022-03-23 16:17
The submission I created is [here](https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=3401688d-3406-4263-bf51-51c08ef9eb6d)

I have tested this for a bit, adding a couple new entities and re-linking. I have not tried with every single specific entity type (e.g. specimen, cell line, organoid etc) but I have tried creating new entity types for protocols, processes and biomaterials and linked them together (and done graph validation and submission afterwards to check that it worked fine with the downstream processes in the submission). Let me know if you would like me to try creating every specific entity type.


## Before hitting submit
### Protocols
-  “Protocol” is not a protocol type entity used in the DCP. Not entirely sure why it’s there, but we should probably hide it/remove it
- Other than that, works as intended! :)

### Processes:
- When adding a new process, it states that the “insidc_experiment_accession” field Is mandatory, but it’s not? Throws an error when trying to add the process without the accession **but** adds the process anyways

### Biomaterials
- Tried with a new donor_organism, worked fine, no issue

### General observations (not related to specific entities)
- The general message when the metadata has been added successfully it’s a bit weird, e.g. `New biomaterial - donor_organism has been successful`. Maybe it could be something like `... has ben added successfully`?
- I think the pagination is not updated successfully (e.g. I’m seeing 7/5 protocols)


## After hitting submit
Added a new protocol (named `the_real_deal`) to test adding protocols after the submission is set to “submitted” and has been exported

- Trying to add a new protocol yields the error `New protocol - collection_protocol has not been successful due to [object Object]` but creates the protocol anyways
- Adding a new entity does not change the submission status (Maybe it’s out of scope for this task?)

## Other (not related to UI changes)
To test the other part of the ticket, I have copied the data in the staging area before and after re-submitting with the new linking. It can be found in the EC2, under the path `/data/eventura/test_new_entity/`, the folder “old” being the staging area the first time I hit submit and the folder “new” being the staging area the second time.

**Comment by MightyAx** [comment] 2022-03-23 16:56
> “Protocol” is not a protocol type entity used in the DCP.

The protocol is still linked to the process though right? (Protocol is still in the HCA schema?)
Perhaps the protocol data is shown on the processes that use them after we export?

> insidc_experiment_accession” field Is mandatory but it’s not?

Do you mean it shouldn't be mandatory in the schema, or that it's mandantoryness doesn't matter to the form?

> Throws an error when trying to add the process without the accession but adds the process anyways

I picked up on this too, validation is reported but not respected, you can make an invalid row, but the validator will mark it as invalid. I might have detected difference between the two save buttons but couldn't reproduce.
Any thoughts @aaclan-ebi?

> Maybe it could be something like `New biomaterial - donor_organism has been added successfully`?

Thanks, Typo! We should fix that.

>  I think the pagination is not updated successfully (e.g. I’m seeing 7/5 protocols)

I noticed this this morning and ~~added a new bug #716~~ have added the tasks in the ticket summary.

> After hitting submit: Adding a new entity does not change the submission status

Yeah, We should implement that, I assumed that editing a submission at all would send it back to draft, @aaclan-ebi?

> New protocol - collection_protocol has not been successful due to [object Object]

In the console log?

> Other not related to UI changes

Don't keep me in suspense @ESapenaVentura 🙀 are old and new different?

**Comment by ESapenaVentura** [comment] 2022-03-24 09:15
>The protocol is still linked to the process though right? (Protocol is still in the HCA schema?)
Perhaps the protocol data is shown on the processes that use them after we export?

Sorry if I wasn't too specific, what I mean is this specific protocol schema: https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/protocol/protocol.json

That one is not used in the system, I don't fully know why it's there (It's always been there, my best guess is that it's been used as a template to create the specific protocols e.g. the library_preparation_protocol)

>Do you mean it shouldn't be mandatory in the schema, or that it's mandantoryness doesn't matter to the form?

It is not mandatory in the [schema](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/process/process.json#L5-L8), but appears as mandatory in the form!

>In the console log?

In the UI! it appeared in the pop-up for errors

> Don't keep me in suspense @ESapenaVentura 🙀 are old and new different?

haha I haven't done an extensive diff but it looks like the links.json updated successfully at least! so that's great :) but I think it needs to be checked more thoroughly

**Comment by MightyAx** [comment] 2022-03-24 10:08
> “Protocol” is not a protocol type entity used in the DCP. Not entirely sure why it’s there, but we should probably hide it/remove it

I see, this schema has been deprecated:
https://schema.staging.data.humancellatlas.org/type/protocol/7.1.0/protocol

We can stop that being returned.
We already do this for the old process schemas that that don't have concreteType = process.

**Comment by aaclan-ebi** [comment] 2022-03-24 10:43
>I picked up on this too, validation is reported but not respected, you can make an invalid row, but the validator will mark it as invalid. I might have detected difference between the two save buttons but couldn't reproduce.

Were there 2 save buttons? The form has no validation in place yet, you'll be able to save anything but once saved the validator should flag the JSON schema errors.

> I think the pagination is not updated successfully (e.g. I’m seeing 7/5 protocols)

Yeah, the no. being displayed after '/' is the expected no. of protocols from the spreadsheet, since entities can be manually added now, they won't match anymore. I don't know how to better display it, let's ask Gabs later.

> Yeah, We should implement that, I assumed that editing a submission at all would send it back to draft

When an entity is added using POST /submissions/id/biomaterials or /submissions/id/protocols or /submissions/id/processes or /submissions/id/files endpoints, state tracking should work fine , ~i haven't got a chance to review the PR yet, let me check...~ It seems that it we're using these endpoints, the state tracking should work fine then 👍

**Comment by MightyAx** [comment] 2022-03-24 11:11
> @aaclan-ebi: Were there 2 save buttons? 

Yep, a big blue one and a small grey one, appears on both new and edit, screenshots below.
![Screenshot 2022-03-24 at 11.08.34.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/076a574f-8cd3-46f9-bd27-83562944e77d)

![Screenshot 2022-03-24 at 11.08.58.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/e7a7f645-ba73-4d9d-82ce-e09b117e0827)

> Yeah, the no. being displayed after '/' is the expected no. of protocols from the spreadsheet

The total number actually does update if you use the UI refresh button, rather than the browser refresh button.

**Comment by jacobwindsor** [comment] 2022-03-28 08:52
@MightyAx to continue to work on this in separate tickets. Don't revert in master

**Closed as completed** 2022-05-09 08:49 UTC
Labels: User Story
