### ISSUE TITLE
Managed Access Deployment

### ISSUE THREAD

**Issue by KociOrges** [ebi-ait/dcp-ingest-central#1029] opened 2024-07-19 13:21 UTC
This ticket tracks the progress of updates for deploying Managed Access changes across several components.

Related ticket [#967](https://app.zenhub.com/workspaces/hca-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/gh/ebi-ait/dcp-ingest-central/967)

See also ticket [#1028](https://app.zenhub.com/workspaces/fairification-63c67b0688ee4e002b2890b3/issues/gh/ebi-ait/dcp-ingest-central/1028) for manual submissions

**Components to be updated:**
- integration-tests
-  ingest-core
-  ingest-graph-validator (potentially - see Additional Notes)
-  exporter
-  ingest-ui
-  state-tracking
-  staging-manager

**Plan for each component:**

**1. integration-tests**
- [x]  Pushing changes to the staging branch
- [x]  Running changes on staging (Gitlab)
- [ ]  Pushing changes to the master branch
- [ ]  Running changes on prod (Gitlab)

**2. ingest-core**
- [x]  Pushing changes to the master branch
- [x]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [x]  **Running manual submissions**: Have tried a couple of manual submissions and are METADATA_INVALID as expected (no files in upload area -> a99e9210-3474-4c08-80dc-9e34d1a754bd, 137e2214-ba9b-44e6-8e60-5033555e5d0b) However, I noticed that Project name is not showing next to the submissions on the Submissions table
- [x]  Repeating Steps 2-3 for production

**3. ingest-graph-validator (potentially - see Additional Notes)**
- [ ] Suggestion: rollback graph validator on dev and rerun a manual test on dev
- [ ]  Pushing changes to the master branch
- [ ]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [ ]  Running manual submissions
- [ ]  Repeating Steps 2-3 for production

**4. ingest-exporter**
- [x]  Pushing changes to the master branch
- [x]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [x]  Running manual submissions
- [ ]  Repeating Steps 2-3 for production

**5. ingest-ui**
- [x]  Pushing changes to the master branch
- [x]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [x]  Running manual submissions
- [x]  Repeating Steps 2-3 for production

**6. state-tracking**
- [x]  Pushing changes to the master branch
- [x]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [x]  Running manual submissions
- [ ]  Repeating Steps 2-3 for production

**7. staging-manager**
- [x]  Pushing changes to the master branch
- [ ]  Deploying to staging (Release prod and Deploy prod steps will be disabled during this stage in the GitLab pipeline)
- [ ]  Running manual submissions
- [ ]  Repeating Steps 2-3 for production

**Additional Notes:**
**broker**: It is just a test change, so not necessary. It can be pushed in the future.
**graph validator**: The change is to use the authenticated ingest API calls. Not sure if it is actually necessary. Suggestion: rollback graph validator on dev and rerun a manual test on dev.
**validator**: There is a managed access branch, but it has not been merged to dev because it is not needed; not necessary for the feature.

**Comment by dipayan1985** [comment] 2024-07-24 08:36
4. monitoring dashboard setup in ingest-staging grafana after getting access
4. Post ingest exporter deployment, first staging submission monitoring URL is [669fa5e2ad1b3e0b95227f5a/9a519a55-333c-4409-add1-f3c479fdd969](https://monitoring.ingest.staging.archive.data.humancellatlas.org/d/0UyrCGsIk/submission-analysis?orgId=1&var-submission_uuid=9a519a55-333c-4409-add1-f3c479fdd969&var-submission_id=669fa5e2ad1b3e0b95227f5a&var-document_type=project&from=now-24h&to=now)

**Comment by dipayan1985** [comment] 2024-07-24 08:37
4. Attempting to initiate graph validation for above submission.

**Comment by dipayan1985** [comment] 2024-07-24 10:05
4. Arsenios triggered the graph validation and it went through, submission is GRAPH valid

**Comment by dipayan1985** [comment] 2024-07-24 10:16
5. deploying ingest-ui to staging

**Comment by dipayan1985** [comment] 2024-07-24 10:41
5. Post ingest-ui deployment, staging submission monitoring URL is [66a0d95dad1b3e0b95228683/e04067ae-40ce-4fd1-b55b-cbac5bec1a2b](https://monitoring.ingest.staging.archive.data.humancellatlas.org/d/0UyrCGsIk/submission-analysis?orgId=1&var-submission_uuid=e04067ae-40ce-4fd1-b55b-cbac5bec1a2b&var-submission_id=66951c61eabbc6206ca56384&var-document_type=project)

**Comment by dipayan1985** [comment] 2024-07-24 11:31
5. Submission is GRAPH_VALID and then we did the PUT to /submissionEvent and submission is in status SUBMITTED. I am expecting EXPORT(ED). Checking with Amnon on if this is expected behaviour.

**Comment by dipayan1985** [comment] 2024-07-25 09:39
5. Trying a new submission to use archive action in /submissionEvent call -> [66a21ac2ad1b3e0b952289a7/458ac070-76a5-4402-a772-0fc5b674e826](https://monitoring.ingest.staging.archive.data.humancellatlas.org/d/0UyrCGsIk/submission-analysis?orgId=1&var-submission_uuid=458ac070-76a5-4402-a772-0fc5b674e826&var-submission_id=66951c61eabb66a21ac2ad1b3e0b952289a7c6206ca56384&var-document_type=project)

**Comment by dipayan1985** [comment] 2024-07-25 12:33
5. The above submission was done with ["Archive", "Export", "Cleanup"] and it got stuck in PROCESSING.

**Comment by dipayan1985** [comment] 2024-07-25 14:45
5. results are the same in manual and integration tests (one at a time) - submissions are stuck in the SUBMITTED state. Notable log message is `Submission event was not accepted`

**Comment by dipayan1985** [comment] 2024-07-25 14:45
4. rolling back ingest-exporter to old version in order to identify issue.

**Comment by dipayan1985** [comment] 2024-07-25 21:35
[ingest_staging_logging.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1cb1b8bd50265695cfd70ad814fdbcb0318b3bf/ingest_staging_logging.txt)

**Comment by dipayan1985** [comment] 2024-07-25 21:37
We are hitting `OptimisticLockingFailureException` in mongo

**Comment by dipayan1985** [comment] 2024-07-26 08:46
Restarted ingest-core and initiated the submission -> [66a36163e8c73060882dcc20/1ce6cd2c-efc7-4963-9ab7-e157ee5039f9](https://monitoring.ingest.staging.archive.data.humancellatlas.org/d/0UyrCGsIk/submission-analysis?orgId=1&var-submission_uuid=1ce6cd2c-efc7-4963-9ab7-e157ee5039f9&var-submission_id=66a36163e8c73060882dcc20)

**Comment by dipayan1985** [comment] 2024-07-26 09:02
[ingest_core_logs.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1RQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99b3c27d946877719ace531002924daf19a16316/ingest_core_logs.txt)
We are hitting:
`2024-07-26 09:44:58	
{"log":"2024-07-26 08:44:58.309 WARN 7 --- [nio-8080-exec-2] o.h.i.c.web.GlobalStateExceptionHandler : Handling ResourceNotFoundException and returning NOT_FOUND response\n","stream":"stdout","time":"2024-07-26T08:44:58.309583696Z"}
	
2024-07-26 09:44:58	
{"log":"2024-07-26 08:44:58.308 WARN 7 --- [nio-8080-exec-2] o.h.i.c.web.GlobalStateExceptionHandler : Caught a resource not found exception argument at 'http://172.20.186.196/files/search/findByValidationJobValidationId'; this will generate a NOT_FOUND RESPONSE. Error message: Resource not found!\n","stream":"stdout","time":"2024-07-26T08:44:58.309246611Z"}
	
2024-07-26 09:44:52	
{"log":"2024-07-26 08:44:52.231 WARN 7 --- [io-8080-exec-35] o.h.i.c.web.GlobalStateExceptionHandler : Handling ResourceNotFoundException and returning NOT_FOUND response\n","stream":"stdout","time":"2024-07-26T08:44:52.231909724Z"}
	
2024-07-26 09:44:52	
{"log":"2024-07-26 08:44:52.231 WARN 7 --- [io-8080-exec-35] o.h.i.c.web.GlobalStateExceptionHandler : Caught a resource not found exception argument at 'http://172.20.186.196/files/search/findByValidationJobValidationId'; this will generate a NOT_FOUND RESPONSE. Error message: Resource not found!\n","stream":"stdout","time":"2024-07-26T08:44:52.231780723Z"}
	
2024-07-26 09:44:52	
{"log":"2024-07-26 08:44:52.198 WARN 7 --- [nio-8080-exec-4] o.h.i.c.web.GlobalStateExceptionHandler : Handling ResourceNotFoundException and returning NOT_FOUND response\n","stream":"stdout","time":"2024-07-26T08:44:52.19895465Z"}
	
2024-07-26 09:44:52	
{"log":"2024-07-26 08:44:52.198 WARN 7 --- [nio-8080-exec-4] o.h.i.c.web.GlobalStateExceptionHandler : Caught a resource not found exception argument at 'http://172.20.186.196/files/search/findByValidationJobValidationId'; this will generate a NOT_FOUND RESPONSE. Error message: Resource not found!\n","stream":"stdout","time":"2024-07-26T08:44:52.198481634Z"}
	
2024-07-26 09:42:27	
{"log":"2024-07-26 08:42:27.210 WARN 7 --- [io-8080-exec-15] o.h.i.c.web.GlobalStateExceptionHandler : Attempt a failed save, likely due to multiple requests, at 'http://172.20.186.196/biomaterials/66a36168e8c73060882dcc24'; this will generate a CONFLICT RESPONSE\n","stream":"stdout","time":"2024-07-26T08:42:27.210816008Z"}
	
2024-07-26 09:42:27	
{"log":"2024-07-26 08:42:27.114 WARN 7 --- [io-8080-exec-21] o.h.i.c.web.GlobalStateExceptionHandler : Attempt a failed save, likely due to multiple requests, at 'http://172.20.186.196/biomaterials/66a36168e8c73060882dcc24'; this will generate a CONFLICT RESPONSE\n","stream":"stdout","time":"2024-07-26T08:42:27.114793581Z"}
	
2024-07-26 09:42:26	
{"log":"2024-07-26 08:42:26.715 INFO 7 --- [ntContainer#0-1] o.h.ingest.file.FileService : File validation state is DRAFT for file with cloudUrl s3://org-hca-data-archive-upload-staging/1ce6cd2c-efc7-4963-9ab7-e157ee5039f9/SRR3562314_1.fastq.gz and submission UUID 1ce6cd2c-efc7-4963-9ab7-e157ee5039f9 \n","stream":"stdout","time":"2024-07-26T08:42:26.715992344Z"}
	
2024-07-26 09:42:26	
{"log":"2024-07-26 08:42:26.692 WARN 7 --- [nio-8080-exec-4] o.h.i.c.web.GlobalStateExceptionHandler : Attempt a failed save, likely due to multiple requests, at 'http://172.20.186.196/biomaterials/66a36168e8c73060882dcc24/validEvent'; this will generate a CONFLICT RESPONSE\n","stream":"stdout","time":"2024-07-26T08:42:26.692820328Z"}
	
2024-07-26 09:42:26	
{"log":"2024-07-26 08:42:26.670 INFO 7 --- [ntContainer#0-1] o.h.ingest.file.FileService : Updating file with cloudUrl s3://org-hca-data-archive-upload-staging/1ce6cd2c-efc7-4963-9ab7-e157ee5039f9/SRR3562314_1.fastq.gz and submission UUID 1ce6cd2c-efc7-4963-9ab7-e157ee5039f9\n","stream":"stdout","time":"2024-07-26T08:42:26.671029382Z"}
	
2024-07-26 09:42:26	
{"log":"2024-07-26 08:42:26.624 WARN 7 --- [io-8080-exec-44] o.h.i.c.web.GlobalStateExceptionHandler : Attempt a failed save, likely due to multiple requests, at 'http://172.20.186.196/biomaterials/66a36168e8c73060882dcc23/validEvent'; this will generate a CONFLICT RESPONSE\n","stream":"stdout","time":"2024-07-26T08:42:26.624878504Z"}`

**Comment by dipayan1985** [comment] 2024-07-26 13:59
We are still investigating the issue with the submission state change not being accepted from SUBMITTED to EXPORT. This is an issue only with staging.
/cc @tburdett /cc @amnonkhen
@amnonkhen, thanks for providing me the help to go into pods and check logs.

**Comment by dipayan1985** [comment] 2024-07-26 17:19
Ruled out both the above errors, CONFLICT and NOT_FOUND, they are non-issues

**Comment by dipayan1985** [comment] 2024-07-29 09:54
Added more logging in state tracker and did a new [PR](https://github.com/ebi-ait/ingest-state-tracking/pull/16), revied by Amnon and merged to dev.

**Comment by dipayan1985** [comment] 2024-07-29 15:05
[logs_comparison_dev_vs_staging.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36e8b07e4dea69c68a1099779e305d90b729b05f/logs_comparison_dev_vs_staging.txt)
Lots of differences in guard while the same submission goes through in dev and staging.

**Comment by dipayan1985** [comment] 2024-07-30 12:33
Revised deployment list:

-     integration-tests
-     ingest-core
-     ingest-graph-validator (potentially - see Additional Notes) **NOT REQUIRED/OPTIONAL - only logger changes**
-     exporter **NOT REQUIRED/OPTIONAL - only logger changes**
-     ingest-ui
-     state-tracking **NOT REQUIRED/OPTIONAL - only logger changes**
-     staging-manager  **NOT REQUIRED/OPTIONAL - only logger changes**

**Comment by dipayan1985** [comment] 2024-07-30 12:58
@amnonkhen, @tburdett, @gabsie - ingest-core and ingest-ui are the impacted projects for this change and they are deployed now to production.

Testing is successful, from submission -> validation -> graph validation -> submission event -> export -> complete

Test submissions:

1. [First](https://monitoring.ingest.archive.data.humancellatlas.org/d/0UyrCGsIk?orgId=1&var-submission_uuid=a8d5a351-2cde-43c8-b5da-4232f709d03b&var-submission_id=66a8db1bf7e68c76e8fe336a)

2. [Second](https://monitoring.ingest.archive.data.humancellatlas.org/d/0UyrCGsIk?orgId=1&var-submission_uuid=eff4093a-08ae-47f1-92c2-914af719850a&var-submission_id=66a8e1aef7e68c76e8fe33ba)

Test jobs:
1. https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1757211
2. https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1757166

**Closed as completed** 2024-07-30 13:48 UTC
Labels: operations, Submissions
