### ISSUE TITLE
Could not submit projects with supplementary files when project is created before submission

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#464] opened 2021-09-27 10:29 UTC
discovered by @ESapenaVentura 
[ref to slack](https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1632738707002700)

**Steps to reproduce:**

1. Create a test project metadata via UI
2. Upload the spreadsheet [https://app.zenhub.com/files/299258791/b4b97e59-d186-4b36-9d97-a357f92ab0a1/download](https://app.zenhub.com/files/299258791/b4b97e59-d186-4b36-9d97-a357f92ab0a1/download)
3. Check the submission manifest link from submission json

**Actual Behavior:**
The actual links and expected links count in the submission manifest doesn't match.
When files are uploaded and submission is valid, the user will never see the submit instructions & button.

**Expected Behavior**
The actual links and expected links count in the submission manifest should match.
When files are uploaded and submission is valid, the user should see the submit tab and button.

~1. go to ingest ui and show [Submission - dcp1219560702433721](https://contribute.data.humancellatlas.org/submissions/detail?uuid=90eec71c-66b2-4bb9-b78c-f8a5328ee8e3)
2. go to *Submit* tab
3. instructions and submit buttons do not appear (see screenshot)
4. notice a JS error in the browser console~

~This happens only for this submission. The submit instructions and button show for all other valid submissions in Prod. For example: [Submission - HealthyAndCirrhoticLiver
](https://contribute.data.humancellatlas.org/submissions/detail?uuid=aab80553-7551-4a9d-becf-68b238d21087)~

~**Error message in browser console:**
'''
main-es2015.6bc03aea3e9741e99099.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'subscribe')
    at e.ngOnInit (main-es2015.6bc03aea3e9741e99099.js:1)
'''
~
**screenshot**
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/cb9fe917-1aa4-48b5-9171-17c27da8ba04)

**Comment by aaclan-ebi** [comment] 2021-09-27 11:11
**Dev notes:**
The submission manifest shows that there is a mismatch actual links/expected links count which may mean that linking hasn't finished.
```
actualLinks: 1500
expectedLinks: 1526
```
Enrique removed the supplementary file and that seems to have fixed the issue.
The submission manifest was showing:
```
actualLinks: 1524
expectedLinks: 1524
```

Still need to investigate the root cause.

**Comment by aaclan-ebi** [comment] 2021-09-28 10:33
It looks like this only happens when the project is created before uploading the spreadsheet. The project isn't being linked in the supplementary file because the importer doesn't do any linking for existing entities.

**Comment by amnonkhen** [comment] 2021-09-28 11:18
@aaclan-ebi Is this a bug?

**Comment by aaclan-ebi** [comment] 2021-09-28 12:32
@amnonkhen yes, it is! Before, projects are being created as part of the spreadsheet. I guess this is something not handled when we allowed the projects to be created first before the submission.

**Comment by amnonkhen** [comment] 2021-10-05 08:52
@aaclan-ebi & @ESapenaVentura to create a ticket for the bug, and document the workaround in this ticket.

**Comment by aaclan-ebi** [comment] 2021-10-05 10:48
I've updated this ticket with new steps to replicate the bug and updated the title to be more specific. 

Workarounds:
1. Remove supplementary files and update project metadata with links to files
2. Put the project worksheet in the metadata spreadsheet

**Comment by gabsie** [comment] 2021-10-06 09:51
Needs investigation, user experience

**Comment by aaclan-ebi** [comment] 2021-10-13 17:37
Created PR for the fix to the importer in ingest-client repo: https://github.com/ebi-ait/ingest-client/pull/30
Waiting for reviews.

**Comment by ofanobilbao** [comment] 2021-10-18 08:37
Alegria still working on the comments. She will work on this today

**Comment by ESapenaVentura** [comment] 2021-10-19 08:38
Merged, deployed to dev and staging, waiting for the test to pass then push to production @aaclan-ebi 

@aaclan-ebi to ask @ESapenaVentura to verify this issue is solved

**Comment by Wkt8** [comment] 2021-10-20 13:09
Have tested as above:

1. Created project in the UI
2. uploaded spreadsheet as a submission
3. Checked the submission manifest 

`"actualLinks" : 1526,
  "expectedLinks" : 1526` 

Shows the expected number of links.

**Comment by ofanobilbao** [comment] 2021-10-21 08:38
@aaclan-ebi will merge into Prod

**Comment by aaclan-ebi** [comment] 2021-10-21 17:16
This is deployed in prod now. 
![Screenshot 2021-10-21 at 18.10.46.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/b3a9475c-79f8-4276-a633-2b67664ca496)
https://gitlab.ebi.ac.uk/hca/ingest-broker/-/pipelines/204639

**Closed as completed** 2022-02-11 10:02 UTC
Labels: bug
