### ISSUE TITLE
"403 Unauthorised" Uploading Spreadsheet to Existing Project

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#808] opened 2022-05-05 14:47 UTC
![Screenshot 2022-05-05 at 15.35.36.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/75fa2ac7-a1db-493e-bbcc-c03f890a49bb)

**Comment by MightyAx** [comment] 2022-05-05 14:51
@MightyAx and @ofanobilbao to investigate tomorrow after stand-up

**Comment by MightyAx** [comment] 2022-05-06 09:43
# Reproduction steps

We have investigated and narrowed the reproduction steps to the following:
1. Create new project from DOI
1. Save a valid project by not ignoring metadata errors
1. Wait for the `project.validationState` to be "Valid" in the API
    - Without the previous two steps the error message could be genuine 
1. Data Upload Tab -> Submit to Project
1. Choose a spreadsheet
1. **Use the option: "Update the project metadata. This will overwrite the existing project metadata."**
1. Click Import Spreadsheet

You will see an error: 

> Operation not allowed while the project has a submission in a non-editable state.

**Comment by MightyAx** [comment] 2022-05-06 09:44
While writing the above steps I was able to get a success using the small dataset test from the wrangler testing folder, this may be a problem with [Oihane's spreadsheet](https://app.zenhub.com/files/261790554/81ea420a-08a7-4e8f-a9b2-1f71322610e1/download).

**Investigation continues...**

**Comment by ESapenaVentura** [comment] 2022-05-13 14:32
Link to [a spreadsheet with a similar issue](https://drive.google.com/drive/folders/1Zq2Ci5XLQVCsdEhqJ9SSSZJkPq0q3Zy3)
The [project that I was trying to update is here](https://contribute.data.humancellatlas.org/projects/detail?uuid=e9f36305-d857-44a3-93f0-df4e6007dc97)

**Comment by ofanobilbao** [comment] 2022-06-29 09:35
Referenced the issue in the Development task related to this. So moving this to Done

**Comment by amnonkhen** [comment] 2022-07-18 12:21
I am not able to reproduce the error message mentioned in this ticket.
I tried doing it with the following spreadsheets:
- the SS2 spreadsheet
- [Oihane's spreadsheet](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/808#issuecomment-1186932486)
- [Enrique's spreadsheet](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/808#issuecomment-1186932492) - tried same DOI and spreadsheet from 10th of May

None of them showed the error message.

**Comment by ESapenaVentura** [comment] 2022-07-18 12:40
I can't replicate the error either - Tried following the steps with Oihane's spreadsheet in staging

**Comment by ESapenaVentura** [comment] 2022-07-19 08:46
Error cannot be replicated - closing ticket!

**Closed as completed by ESapenaVentura** 2022-07-19 08:46 UTC
Labels: bug
