### ISSUE TITLE
When editing a project field, the Wrangling status disappears

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#872] opened 2022-11-11 10:22 UTC
Bug. 
When editing a project field, the Wrangling status disappears. We have checked this with two statuses.

Steps to reproduce:

1. Open up a Project with a status 'Eligible' or 'in Progress', could be for other statuses as well
2. Change the Project label to something else. Ignore validation errors and Save. 
3. Check the project Admin tab - Wrangling status is not only 'Not specified', but the whole box is missing (see screenshot)
4. Sometimes we see this on the first time, sometimes on the second time you go and Edit this project.

![Screenshot 2022-11-11 at 10.17.41.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/6e775d62-1897-4812-9ee8-88c541c7f25d)
![Screenshot 2022-11-11 at 10.17.03.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/6592bc6a-7cc0-42a9-9f2d-c380d01e31d8)![Screenshot 2022-11-11 at 10.16.42.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/83dee8ef-5165-497c-aa6c-b8d2c2982150)

**Comment by gabsie** [comment] 2022-11-16 11:00
This actually happens when I create a project from scratch in backoffice.

**Comment by MightyAx** [comment] 2022-11-16 16:46
Does it happen when your project has no submissions?

**Comment by gabsie** [comment] 2022-11-16 16:48
yep when I tested, but worth it to also check the scenario of having an existing submission and then editing project details.

**Comment by Mil-m** [comment] 2022-11-16 16:50
as I didn't receive this error on the project with submission I'll try it with the clear project without any submissions
@gabsie @MightyAx

**Comment by Mil-m** [comment] 2022-11-16 19:03
(1) I don't see the 'Wrangling status' field after creating a new project (at staging URL), is it a normal case? I assumed to see the 'N/A' for example (as in the other fields: Wrangling priority / Release number)

**Comment by Mil-m** [comment] 2022-11-16 20:24
so far I don’t see an error either on 'staging' or on the 'dev'

**Comment by MightyAx** [comment] 2022-11-17 09:53
- [ ] @Mil-m to book meeting with @ofanobilbao for issue identification.

**Comment by ofanobilbao** [comment] 2022-11-17 12:24
@Mil-m and me had a chat just now. Some of the issues that Gabby and me were encountering, did not happen when I was testing in staging with her. However, I've also noticed that some of the projects in Prod that I manually added and where this issue happened, I had edited them for their status to be Eligible and I see from the History tab that 12h later the status was removed altogether.

Milena will wait until tomorrow to check the two projects in staging we were looking at, to see if 12h later as well the status disappears. If nothing happens, then something in between 14th November and today has resolved the issues by themselves?

Projects she will check tomorrow:

https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=06c2019c-46ad-4196-9c5b-b108c65ef6be

https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=e5e7f760-7aee-491f-be3d-df34d5238c2c

**Comment by gabsie** [comment] 2022-11-17 12:32
were we testing before in dev or prod? @ofanobilbao

**Comment by ofanobilbao** [comment] 2022-11-17 13:08
@gabsie this was only in staging. It was only to clarify with Milena what the issues where. Once she observes the issues herself, then she might be able to start understanding why this is happening.

**Comment by idazucchi** [comment] 2022-11-18 09:50
the bug couldn't be reproduced but a trace remains in the History tab 
the status usually disappears after 12h, but in this case the status has remained 
@ofanobilbao will add more details

**Comment by ESapenaVentura** [comment] 2022-11-21 09:39
@ofanobilbao to add screenshots, although bug does not seem to be reproducible so we may need to move this to waiting

**Comment by Wkt8** [comment] 2022-11-22 09:45
Bug does not seem to be reproducible so moving to waiting.

**Comment by ofanobilbao** [comment] 2022-11-22 09:47
@ofanobilbao to add some screenshots showing when this happened at least for a few examples

**Comment by Wkt8** [comment] 2022-11-29 09:44
@ofanobilbao to add some screenshots and then close the ticket because it does not seem to be reproducible.

**Comment by ofanobilbao** [comment] 2022-11-29 10:22
When I was going through the potential Kidney Atlas project list:
I added several to Ingest, triage them and labelled them Eligible. See screenshot of list of Projects that all of a sudden I discovered had no Status anymore.![List of Projects that should be Eligible.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/68207038-7ffd-4e42-8065-ba86a4c166f7)

**Comment by ofanobilbao** [comment] 2022-11-29 10:24
Find one specific example (others were the same) of a project that I added for that Atlas effort. I added the project, triaged it and labelled it Eligible and as per the history (another screenshot) I can see status was removed in about 12h.
![Example of Proj labelled Eligible.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/ee98cd0c-42c6-4feb-9cff-e2e84a680e81)
![Example of Proj labelled Eligible sc2.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/dccd2e77-0cf5-490f-a91c-007895e797c1)

**Comment by ofanobilbao** [comment] 2022-11-29 10:25
2nd example of the same situation:
![Example Proj 2 Sc.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/45ebf1e7-ccd4-461a-98e3-abc41844de34)
![Example Proj 2 Sc2.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/78d923ef-6679-4db1-bf66-09c7680b79b2)

**Comment by ofanobilbao** [comment] 2022-11-29 10:33
Example of a project that was on Submitted status and went to No status.
![Example Proj Submitted to none.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/52708ee7-a3e8-40b0-bcc1-55bad22c2558)
![Example Proj Submitted to none sc2.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/e5ed97aa-9714-4daf-9b93-f5e6e63624ef)
![Example Proj Submitted to none sc3.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/1594d39d-76f7-4793-9c53-f22bd1df0af9)

**Comment by ofanobilbao** [comment] 2022-11-29 10:35
As per our discussion in stand-up earlier today, I am closing the ticket with all possible screenshots I took. In case we need to re-surface the ticket because the issue happens again. At the minute the errors seem to not be taking place. So the bug is either resolved or not reproducible anymore.

**Closed as completed by ofanobilbao** 2022-11-29 10:35 UTC
Labels: bug
