### ISSUE TITLE
user indication of data file export with updated metadata

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#160] opened 2021-02-02 21:47 UTC
## User Story
As a wrangler I want to indicate if the data files should be exported or not, rather than the system deciding.

The data files will not always be present in the staging bucket and updates will still need to be made without exporting all the data files. (Eg. for DCP1 datasets) in this case the user should indicate if the files should be exported or not.

## Acceptance Criteria
user can indicate if data files should be exported as part of the update
updated metadata can be exported without data files being exported and without data files being present in the staging bucket
SOP for updates is updated

- [ ] [subtask 253 for UI review of solution](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/253)

**Comment by aaclan-ebi** [comment] 2021-02-22 11:48
DCP2 MVP datasets would also need this feature.

**Comment by aaclan-ebi** [comment] 2021-03-15 15:33
@rays22 @yusra-haider Should we add test cases in the Updates tab of the test plan https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/edit#gid=1643975178 for this user story?

**Comment by rays22** [comment] 2021-03-24 18:35
### Test plan

* Create test data (that includes sequence data and all HCA curated metadata).
* Create test project and upload test data
    - upload [metadata spreadsheet](https://drive.google.com/file/d/1aldAFkr4S1PUqhNyrVAaEcrK0BDNScny/)
        - metadata should pass validation
    - transfer sequence data files to Ingest bucket
        - data files should pass validation
* Export 1
* Update some of the metadata in Ingest UI. 
* Test export.
    * Test case 1: exporting without data files.
    * Test case 3: exporting an update with data files.
    * Test case 3: exporting an update with data files.
    * Test case 4: exporting updated data files without metadata update.

There are three options in the UI at the time of exporting. I am not going to select the first option ever for these tests:
1. Submit to the EMBL-EBI public archives and get accessions. Data will be public on (unset) as specified in the release date of this project.
2. Submit only metadata to the Human Cell Atlas.
3. Submit metadata and data to the Human Cell Atlas. This will be made public with the next snapshot.

### Executing the test plan:

* Test case 1: exporting without data files. **PASS**
This is not a test of updates, but it does emulate at leas one real word use case, the case when we are exporting expression matrices without raw sequence for managed access projects or data from living human donors.

- [x] Submit only metadata to the Human Cell Atlas.

* Test case 2: exporting an update without data files. **PASS**
I added a project contributor via the UI. This triggers re-validation and allows export.

- [x] Submit only metadata to the Human Cell Atlas.

Checked what has been exported to the staging bucket using `gsutil`.

* Test case 3: exporting an update with data files. **PASS**
I am forced to make some updates in the metadata, otherwise Ingest UI does not allow me to export data files only.
    * Test 3a: added Accession Time Frame via the UI <-- does NOT allow re-export!!
    * Test 3b: added `NA` as `Grant title` via the UI <-- does allow re-export

- [x] Submit metadata and data to the Human Cell Atlas. This will be made public with the next snapshot.

Checked what has been exported to the staging bucket using `gsutil`. Did check the number of exported data files and their sizes, but did not check checksums of the files to see if the exported data files differ between the aws and gs buckets.

* Test case 4: exporting updated data files without metadata update: **FAILED** to create a test setup in Ingest.
As a wrangler, how can I replace a sequence data file in an ingest s3 bucket using `hca-util sync` in a way that would allow me to re-export the project?
As far as I am aware, I am supposed to use exclusively `hca-util sync` transfer sequence data files to an Ingest submission bucket.

**Comment by rays22** [comment] 2021-03-25 10:31
@clairerye 
If I rephrase the user story as in case 1 below, then this issue is solved. However, I think there remain two other use cases that are not yet solved.

1.
As a wrangler, I would like to decide if I want to export the sequence data files alongside the metadata or not. This can be the both the first export of the dataset or an export with metadata updates.
For example, I do not want to export the sequence data files, because there are privacy and/or managed access issues related to living human donors, but I still want to export the metadata the first time or update it.  

2.
As a wrangler, I would like to export sequence data files without exporting any wrangler-editable metadata updates.

3.
As a wrangler, I would like to export some or all the sequence data files in a previously exported dataset. This may involve updating previously exported data files.

**Comment by rays22** [comment] 2021-03-25 11:49
> * Test case 4: exporting updated data files without metadata update: **FAILED** to create a test setup in Ingest.

@yusra-haider : I have tried the data file update and export without using the `Delete Upload Area` option in the UI before I upload an updated sequence data file to the Ingest submission upload area. It worked, so I am changing the status of `Test case 4` from **FAIL** to **PASS**

1. Update one data file in hca-util upload area using `hca-util upload -o`.
2. Copy (using `hca-util sync`) the updated data file that has the same file name as the one in the previous submission to the Ingest submission upload area.
3. Does it trigger re-validation of the data files? Can I re-export the dataset?
Yes, the new file re-triggers file validation and Ingest UI allows me to do an export again.
4. Choose the UI option `Submit metadata and data to the Human Cell Atlas. This will be made public with the next snapshot.`
5. Check what has been exported.
I can confirm that **only the updated sequence data file** was exported compared with the previously exported data. 

```
< 343.84 MiB  2021-03-25T07:42:58Z  gs://broad-dsp-monster-hca-dev-ebi-staging/staging/3358e37e-ed47-4955-bc99-8f1884765b5c/data/S01_CDNA_S1_L002_R2_001.fastq.gz
---
>      131 B  2021-03-25T11:25:45Z  gs://broad-dsp-monster-hca-dev-ebi-staging/staging/3358e37e-ed47-4955-bc99-8f1884765b5c/data/S01_CDNA_S1_L002_R2_001.fastq.gz
```

**Comment by clairerye** [comment] 2021-03-25 14:19
Thanks @rays22 for your exhaustive testing of this and for the extra tests to get test case 4 working.

**Comment by gabsie** [comment] 2021-03-25 15:30
hi everyone, 
I think I will not be stopping @yusra-haider 's upload to prod if for metadata updates the current way of working works for Ray.
I am creating a ticket for myself to do a review with regards to user-focused texts and design, but that will fall into a different ticket for me.

Thanks to Ray as well, I will be in touch with him

Gabs

**Comment by clairerye** [comment] 2021-08-02 11:05
have been using this successfully for multiple releases

**Closed** 2021-09-21 14:23 UTC
Labels: User Story, Small
