### ISSUE TITLE
Unable to download spreadsheet from ingest

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#632] opened 2022-01-26 18:02 UTC
**Describe the bug**
I am unable to download a spreadsheet for project NucleiMultiplexHashing 

**To Reproduce**
1. Go to the [submission page](https://contribute.data.humancellatlas.org/submissions/detail?uuid=e6dca5ce-60b2-4087-97bd-fb32b20db01a&project=dc1a41f6-9e09-42a6-959e-3be23db6da56) 
2. Click on Download spreadsheet
3. Wait
4. Service unavailable message appears - the waiting message is overlaid on top

**Expected behaviour**
After a certain waiting time I should be able to download the spreadsheet

**Screenshots / Logs**
![Screenshot 2022-01-26 at 17.59.50.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/3628c9ac-aa3d-4c56-8984-7524429915c2)

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by ipediez** [comment] 2022-02-02 14:49
This is blocking one of my datasets too

**Comment by gabsie** [comment] 2022-02-03 09:06
Hey @aaclan-ebi - is this something you have taken? I think we need to escalate this investigation :)

**Comment by Wkt8** [comment] 2022-02-03 09:38
https://drive.google.com/open?id=1vVQJon-IBKhQnDIaltaHtFRFz3LftI0E&authuser=mshadbolt%40ebi.ac.uk&usp=drive_fs

**Comment by aaclan-ebi** [comment] 2022-02-03 10:38
Interesting, i see the following error in prod logs for Ida's submission
```
ingest-broker-67968b8d57-zc5xg ingest-broker [app.py:1458 -        log_exception() ] 2022-02-03 09:56:32,698 - broker_app - ERROR - Exception on /submissions/e6dca5ce-60b2-4087-97bd-fb32b20db01a/spreadsheet [GET]
ingest-broker-67968b8d57-zc5xg ingest-broker Traceback (most recent call last):
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
ingest-broker-67968b8d57-zc5xg ingest-broker     response = self.full_dispatch_request()
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
ingest-broker-67968b8d57-zc5xg ingest-broker     rv = self.handle_user_exception(e)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
ingest-broker-67968b8d57-zc5xg ingest-broker     return cors_after_request(app.make_response(f(*args, **kwargs)))
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
ingest-broker-67968b8d57-zc5xg ingest-broker     rv = self.dispatch_request()
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
ingest-broker-67968b8d57-zc5xg ingest-broker     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/broker/submissions/routes.py", line 21, in export_to_spreadsheet
ingest-broker-67968b8d57-zc5xg ingest-broker     workbook = ExportToSpreadsheetService(app.ingest_api).export(submission_uuid)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/broker/submissions/export_to_spreadsheet_service.py", line 17, in export
ingest-broker-67968b8d57-zc5xg ingest-broker     flattened_json = self.downloader.convert_json(entity_list)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/downloader.py", line 18, in convert_json
ingest-broker-67968b8d57-zc5xg ingest-broker     return self.flattener.flatten(metadata_list)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/flattener.py", line 21, in flatten
ingest-broker-67968b8d57-zc5xg ingest-broker     self._flatten_entity(entity)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/flattener.py", line 37, in _flatten_entity
ingest-broker-67968b8d57-zc5xg ingest-broker     embedded_content = self.embed_link_columns(entity)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/flattener.py", line 72, in embed_link_columns
ingest-broker-67968b8d57-zc5xg ingest-broker     self._embed_input_ids(entity, embedded_content)
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/flattener.py", line 116, in _embed_input_ids
ingest-broker-67968b8d57-zc5xg ingest-broker     input_ids_ids = [i.content['biomaterial_core']['biomaterial_id'] for i in inputs]
ingest-broker-67968b8d57-zc5xg ingest-broker   File "/app/src/hca-ingest/ingest/downloader/flattener.py", line 116, in <listcomp>
ingest-broker-67968b8d57-zc5xg ingest-broker     input_ids_ids = [i.content['biomaterial_core']['biomaterial_id'] for i in inputs]
ingest-broker-67968b8d57-zc5xg ingest-broker KeyError: 'biomaterial_core'
ingest-broker-67968b8d57-zc5xg ingest-broker [_internal.py:225 -                 _log() ] 2022-02-03 09:56:32,700 - werkzeug - INFO - 10.70.1.47 - - [03/Feb/2022 09:56:32] "GET /submissions/e6dca5ce-60b2-4087-97bd-fb32b20db01a/spreadsheet HTTP/1.1" 500 -
```

**Comment by aaclan-ebi** [comment] 2022-02-03 14:17
Seems like the downloader implementation is not able to handle datasets with file to file linking (e.g. sequencing file to analysis file linking). I'll work on a fix for this.

**Comment by idazucchi** [comment] 2022-02-04 09:57
@aaclan-ebi to work on this

**Comment by aaclan-ebi** [comment] 2022-02-07 14:42
@idazucchi it seems that the dataset is using a protocol from a different project/submission d58f1239-387d-4a39-bc79-bb29b765863d , https://api.ingest.archive.data.humancellatlas.org/protocols/60feb094ad68e2545d23bd93  Is this intended?

@ipediez could you paste here the UI link to your dataset?

Thanks!

**Comment by aaclan-ebi** [comment] 2022-02-08 09:22
Re my question above, @idazucchi confirmed that the protocol linking was fixed yesterday.

PRs ready for review:
https://github.com/ebi-ait/ingest-client/pull/43
https://github.com/ebi-ait/ingest-core/pull/112

**Comment by ipediez** [comment] 2022-02-08 09:40
Submission UUID: `85b5d566-bb78-4bed-89e6-2f44e7b6bd48`
Project: `5b328561-4a97-40ac-b7ad-6a90fc59d374`

**Comment by prabh-t** [comment] 2022-02-15 09:48
require one more review/approval.

**Comment by aaclan-ebi** [comment] 2022-02-16 11:27
Tested Irene's spreadsheet in staging: https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=06923b5d-942d-430f-99c2-b56f64caa96e 

The spreadsheet was downloaded successfully.

Will promote to prod.

**Comment by aaclan-ebi** [comment] 2022-02-16 15:01
Hi @ipediez & @idazucchi The spreadsheet was generated successfully for both of your submissions in prod. You can check and download them now.

**Closed as completed** 2022-03-24 03:07 UTC
Labels: bug
