### ISSUE TITLE
Force re-validation of metadata after linking changes

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#517] opened 2021-11-01 13:18 UTC
**Describe the bug**
When modifying the linking of a submission via the UI (Or spreadsheet when supported), I want the submission to be re-validated so that I can run the graph validator again

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the UI
2. Create a valid submission
3. Run the graph validator on the "Validate" tab
4. Update the linking (e.g. Take out all the collection protocol links in the processes)
5. Can't re-validate again

**Expected behaviour**
I would expect to be able to re-run the graph validator as the submission has changed and needs to be re-validated.

**Comment by ofanobilbao** [comment] 2021-11-08 09:40
Still in progress. Yusra is looking into options. @yusra-haider and @amnonkhen to meet to discuss after stand up

**Comment by yusra-haider** [comment] 2021-11-10 13:08
draft PR raised here: https://github.com/ebi-ait/ingest-core/pull/93

The current code changes are in dev environment and can be experimented around with the UI.

Here's the testing I've done so far on dev:
used the submission: [CervicalCancerLandscape](https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=3864f954-4707-42d7-8782-735a8b6c83a4)

All of these tests were performed with the submission state as Valid
1. unlinking protocol(s) from a process sets the state for that process to Draft. This triggers the overall submission state to go into Draft and changes the graph validation state back to Pending, allowing the user to revalidate

2. unlinking input or output biomaterial(s) from a process sets the state for those biomaterial(s) to Draft. This triggers the overall submission state to go into Draft and changes the graph validation state back to Pending, allowing the user to revalidate

3. Unlinking output file(s) from a process sets the state for those file(s) to Draft. This triggers the overall submission state to go into Draft and changes the graph validation state back to Pending, allowing the user to revalidate


further to-dos:

- [x] fix the automated tests in the code
- [ ] @aaclan-ebi reported a [bug](https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=0ede8986-a536-4026-a283-10c8412a4435) where when a spreadsheet is uploaded, the error ```Received an HTTP 400 from http://172.20.37.89/biomaterials/618bafd75bcfef2055e2a4c6/project: http://172.20.37.89/biomaterials/618bafd75bcfef2055e2a4c6/projectjava.lang.ClassCastException@6b3ce866``` gets thrown. I believe this is a side effect of the code changes I've made and am looking into fixing this

cc: @amnonkhen @gabsie

**Comment by ipediez** [comment] 2021-11-11 09:40
@amnonkhen to take a look at this

**Comment by ofanobilbao** [comment] 2021-11-12 09:49
@amnonkhen gave her a few ideas to progress. But she is still not unstuck. @amnonkhen and @yusra-haider to continue with this today

**Comment by yusra-haider** [comment] 2021-11-12 14:15
could not reproduce the bug @aaclan-ebi pointed out.
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=0fbad012-5a18-4b50-84d5-7e0284b8cb2f

I was able to successfully upload the same spreadsheet, successfully

**Comment by yusra-haider** [comment] 2021-11-12 14:18
PR raised, waiting for approvals in order to merge it

**Comment by yusra-haider** [comment] 2021-11-12 15:13
PR merged, ticket is ready for wrangler testing

**Comment by ke4** [comment] 2021-11-12 16:28
@yusra-haider I think you broke the integration test with this change. Could you please review it? Tx

**Comment by ESapenaVentura** [comment] 2021-11-15 09:01
@yusra-haider should I test this before you address the comment above?

**Comment by ESapenaVentura** [comment] 2021-11-15 09:41
@aaclan-ebi to continue investigation. 

Integration test is still broken, submissions get deleted and archiving starts. @ke4 to help with investigation

@aaclan-ebi to check and come back to enrique later about testing

**Comment by ESapenaVentura** [comment] 2021-11-15 13:46
Uploaded a project to test, files got stuck in validating https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=37f4c191-fbf3-4d58-915a-59d79d07185d&project=cc4e44c1-af18-4a25-abec-b2504cbd606d

**Comment by aaclan-ebi** [comment] 2021-11-16 09:43
@ESapenaVentura tested in staging but files were stuck in Validating in staging.

**Comment by aaclan-ebi** [comment] 2021-11-16 10:47
@ESapenaVentura the changes for this user story isn't in staging yet. That test submission you did in staging was affected by the core outage yesterday morning, the files validation result didn't make it to core because core was down. Please retry.

Also, to set record straight, that the changes for this story didn't break the integration tests in dev. 

There is a current issue in dev that we noticed in the test submissions. The linking seems fine but this error was flagged for some reason.

```
Received an HTTP 400 from http://172.20.37.89/processes/61924a7c220ce661c26b055b/project: http://172.20.37.89/processes/61924a7c220ce661c26b055b/projectjava.lang.ClassCastException@22b3a465
```

@yusra-haider , @ke4 and I added some stack trace logging in dev, please see thread: https://embl-ebi-ait.slack.com/archives/C01Q3RMJZ6K/p1636978310026800

**Comment by gabsie** [comment] 2021-11-23 10:55
hey @yusra-haider and @jacobwindsor - is this now ready to be in prod? I kind of lost the story here..

**Comment by jacobwindsor** [comment] 2021-11-25 09:44
Yes, this is in prod.

We may have to revert this due to issues it causes with linking as mentioned by @aaclan-ebi above

**Comment by jacobwindsor** [comment] 2021-11-25 15:53
This has been reverted. Please see [slack thread](https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1637840940185000) for more explanation.

We will investigate this and try to fix it

**Comment by amnonkhen** [comment] 2021-11-29 09:50
@yusra-haider and @jacobwindsor Friday debug session did not yield to root cause for the problem.

**Comment by amnonkhen** [comment] 2021-11-29 09:53
@jacobwindsor & @amnonkhen to continue investigating.

**Comment by jacobwindsor** [comment] 2021-11-29 17:30
To replicate the issue:

1. Checkout `ingest-core` from before the revert
2. Run `ingest-core`, `ingest-UI`, and `ingest-broker`
3. Upload the SS2 integration test submission
4. You will see the error
5. To replicate the specific problem. You can:
  1. Locate the process that is not linked to the project (probably the last one)
  2. `curl -X PUT --data 'http://localhost:8080/projects/<project_id>' http://localhost:8080/processes/<process_id>/project -H "content-type: text/uri-list"`

**Comment by idazucchi** [comment] 2021-11-30 09:47
more investigation is required

**Comment by ofanobilbao** [comment] 2021-12-02 09:42
@aaclan-ebi will have a meeting with @amnonkhen on this today

**Comment by ami-day** [comment] 2021-12-03 09:37
@jacobwindsor and @aaclan-ebi are going to discuss this today

**Comment by aaclan-ebi** [comment] 2021-12-03 14:27
Assigning @amnonkhen @yusra-haider as primary code reviewers
PR: https://github.com/ebi-ait/ingest-core/pull/101

**Comment by gabsie** [comment] 2021-12-06 13:29
can we also get this to prod if reviewed? :) @amnonkhen

**Comment by ami-day** [comment] 2021-12-07 09:50
@aaclan-ebi needs to investigate this further

**Comment by aaclan-ebi** [comment] 2021-12-08 20:11
Hi @amnonkhen @yusra-haider This is ready for review again: https://github.com/ebi-ait/ingest-core/pull/101/files. Please check. Thanks!

**Comment by aaclan-ebi** [comment] 2021-12-13 09:39
Waiting for reviews.

**Comment by aaclan-ebi** [comment] 2021-12-13 09:41
@yusra-haider @amnonkhen to review today.

**Comment by ESapenaVentura** [comment] 2021-12-14 09:40
Overlaps with #546

**Comment by ke4** [comment] 2021-12-16 09:54
This is going to be tested together with #546.

**Comment by ESapenaVentura** [comment] 2021-12-17 16:27
Tested (See comment in #546). Works fine!

**Closed as completed** 2022-02-11 10:01 UTC
Labels: bug
