### ISSUE TITLE
Operation not allowed during spreadsheet import

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#858] opened 2022-09-23 20:47 UTC
**Describe the bug**
Uploading a spreadsheet to staging raises this error and doesn't seem to update the project information.
![Screenshot 2022-09-23 at 21.40.52.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/7a926e53-c974-44ae-b431-ae4616a185c8)

This is possibly due to the fact that ingest tries to update the project right after creating the submission which is then in the pending uneditable status
spreadsheet used [here](https://docs.google.com/spreadsheets/d/1pqT1sT2CmJ2d_UTFVswRfzXHIzpABN44/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to staging
2. Upload the spreadsheet to an existing project ticking the update project box
3. Wait

**Expected behaviour**
I expect the spreadsheet to be uploaded correctly and to update the project information

**Environment**
- [ ] prod
- [x] staging
- [ ] dev

**Browser**
- [ ] Chrome
- [ ] Safari
- [ ] IE
- [x] Firefox

**Comment by Mil-m** [comment] 2022-11-22 02:14
In my tests, this error occurred on the **dev** but not on the **staging**
...
and I don't see this error more...

**Comment by Mil-m** [comment] 2022-11-22 03:40
both on **staging** and **dev** - is it OK?
->
https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/637c45c347c42201491853ea/submissionManifest
https://api.ingest.dev.archive.data.humancellatlas.org/submissionManifests/637c45cd47c42201491853eb/submissionEnvelope
...
https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/637c45c347c42201491853ea/commitInvalidEvent
```
<ExceptionInfo>
<url>https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/637c45c347c42201491853ea/commitInvalidEvent</url>
<exceptionMessage>Resource not found!</exceptionMessage>
</ExceptionInfo>
```
https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/637c45c347c42201491853ea/commitGraphInvalidEvent
```
<ExceptionInfo>
<url>https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/637c45c347c42201491853ea/commitGraphInvalidEvent</url>
<exceptionMessage>Resource not found!</exceptionMessage>
</ExceptionInfo>
```

**Comment by MightyAx** [comment] 2022-11-22 15:25
## What we've tested (on dev):
### update project from spreadsheet flow:
1. new project (blank, ignore validation)
2. upload spreadsheet, update project
3. project is updated, marked as valid, submission is imported, only invalid due to missing files
4. test passed

### New project flow:
1. new project, fill out project form
2. upload spreadsheet, DO NOT update project
3. submission is imported, only invalid due to missing files
4. test passed

**Comment by Mil-m** [comment] 2022-11-23 16:33
I re-produced this error on the 'staging' but for the new projects (not for already existed)
A new project might be with the filled-out fields or not (the error will be in any case)

**Comment by ofanobilbao** [comment] 2022-11-24 09:42
It makes sense to reproduce this locally. @Mil-m to ask help from @MightyAx

**Comment by gabsie** [comment] 2022-11-28 14:38
What is the status here? @Mil-m ?

**Comment by Mil-m** [comment] 2022-11-28 14:55
Hi @gabsie 
Is it Ok if I'll update it today evening or tomorrow morning?

**Comment by Mil-m** [comment] 2022-11-29 00:29
For this moment ->
need to fix the 'import a spreadsheet' request in Postman to receive a successful import (it will not guarantee that there will be any logs about the current error, possibly we will have to look at the logs inside docker containers)

**Comment by idazucchi** [comment] 2022-12-05 09:39
@MightyAx and @Mil-m to discuss this today

**Comment by ofanobilbao** [comment] 2022-12-12 09:39
@Mil-m and @MightyAx to talk when available

**Comment by ofanobilbao** [comment] 2022-12-12 09:39
@Mil-m and @MightyAx to talk when available

**Comment by Mil-m** [comment] 2022-12-20 16:08
How to reproduce this error locally:
- launch ingest-core (with 2 docker containers)
- launch ingest-broker
- (don't forget to delete the submission for the current project)
- use script to import the submission

the error is here:
```java
    SecurityAspetcs.java ->
        if (!isAllowed) {
            throw exceptionClass.getDeclaredConstructor().newInstance();
        }
```
(we can receive this exception in the 'run' mode but not in the 'debug' mode)

2022-12-20 16:43:24.374 ERROR 66367 --- [nio-8080-exec-9] o.h.i.c.web.GlobalStateExceptionHandler  : Not allowed exception encountered on PATCH request to resource http://localhost:8080/projects/63a1cb41b35a0319ba8850b6

**Comment by amnonkhen** [comment] 2022-12-21 12:36
Some new developments with this bug:
on dev it happens occasionally, with some relation, to the duration of the wait between project creation and spreadsheet upload.
If the duration is short - the problem happens always, and is noticeable in the ui and in the logs also when doing a programmatic submission.
When we wait a long time, over a minute or so, the problem is less like to happen. Sometimes it shows in the ui "submission not editable", sometimes it does not show the error in the ui, but the project metadata is not updated, evident by validation errors in the ui as well as an ERROR for the PATCH to project in the logs.

I scheduled a meeting with the devs to discuss.

**Comment by idazucchi** [comment] 2022-12-22 09:40
Milena and Alexie to discuss this today

**Comment by MightyAx** [comment] 2022-12-22 11:31
### Ideas
In [ingest-client importer](https://github.com/ebi-ait/ingest-client/blob/7b64eb0cd0c6e02d317d7dd610ac377361a304b7/hca_ingest/importer/importer.py#L86):
 - poll for submission_url `.editable` True
    - Then patch project 

or in ingest-core
- change [this check allowed statement](https://github.com/ebi-ait/ingest-core/blob/b1fd10df80a94ef7955c83c36b9428c50c862f2d/src/main/java/org/humancellatlas/ingest/project/web/ProjectController.java#L91) to `isSystemEditable`

**Comment by ESapenaVentura** [comment] 2022-12-23 09:40
Preference towards changes in ingest-client importer rather than core

**Comment by amnonkhen** [comment] 2022-12-23 09:43
The change should be polling for `isEditable` on the submission, then run [`self.submitter.update_entity(project)`](https://github.com/ebi-ait/ingest-client/blob/7b64eb0cd0c6e02d317d7dd610ac377361a304b7/hca_ingest/importer/importer.py#L86)

**Comment by Wkt8** [comment] 2023-01-13 09:38
Error found, fix attempted, and now error is no longer reproducible after following initial steps. 

Error has now been fixed.

**Comment by MightyAx** [comment] 2023-01-16 11:51
This was not unit tested, and failed unit tests.

I've opened a new PR which moved the polling functionality into the ingest_api class, making it easier to unit test.

**Comment by MightyAx** [comment] 2023-01-16 11:56
Also, I think the polling feature as written would always hit the cache without checking the source.
I've fixed that in [PR#65](https://github.com/ebi-ait/ingest-client/pull/65)

**Comment by MightyAx** [comment] 2023-01-17 11:48
### Red Herring Error: No Such Table
There was an [integration test error](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1130166#L40)
[An error occurred importing the file. no such table: responses](https://monitoring.ingest.dev.archive.data.humancellatlas.org/goto/2KKZcmTVk)
![image.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/d338c8e7-4a9d-4a2a-84dd-a9f5c567901e)

From memory I think this error occurs because the underlying sqllite gets reset (possibly due to threading) and requests-cache doesn’t just re-init, it throws this error.
I’ve seen this intermittently since we introduced requests-cache

But when I re-ran the test I got a different error, it's possible the no such table: responses error is only masking other errors, hence why it is intermittent.

**Comment by MightyAx** [comment] 2023-01-17 11:50
### Actual Error
On [repeating the test](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1130213), [the 'actual' error is revealed](https://monitoring.ingest.dev.archive.data.humancellatlas.org/goto/znQJ2mTVk)
`XlsDownloader' object has no attribute 'convert_json'`

### Fixing it
New broker PR #49 has been merged and fixes the integration tests on dev, deployment to staging in progress

**Comment by MightyAx** [comment] 2023-01-17 11:57
### Staging integration tests
The [first bulk upload](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1130325) still suffered the [no such table issue,](https://monitoring.ingest.staging.archive.data.humancellatlas.org/goto/vYrYJioVk)

Restarting the integration tests succeeds.
Perhaps the no such table issue only effects the first bulk import each time the broker restarts?

**Comment by MightyAx** [comment] 2023-01-17 11:58
@Mil-m the staging environment is ready for your testing.

**Comment by Mil-m** [comment] 2023-01-17 14:54
@MightyAx I don't see any problems on dev (uploaded 2 spreadsheets for new projects). Should I check the same on staging also? Or should I check something else there?

**Comment by MightyAx** [comment] 2023-01-17 14:56
yes, please test on the **staging** environment.

**Comment by Mil-m** [comment] 2023-01-17 16:07
@MightyAx Don't see any problems on staging also:
staging ->
https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=b090143f-6d5d-4d8c-a63a-244a986a88f4&project=9dcc88af-b50f-47c8-a93a-f0ef1e4cef3d
https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=e672e0d6-2eaa-4e95-ba08-a2ee01008174&project=dff56200-4091-48e8-8174-fe6a479be8da
dev ->
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=613496e3-4b71-4c8c-831b-39674ee4cd15&project=a2013e2d-2bfd-4589-bf02-4e7f5ab479c3
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=9760f3fd-8ddb-46f0-9e68-8477f1c488c5&project=60a9551f-880b-4937-b8db-10f12ed2b40a

**Comment by MightyAx** [comment] 2023-01-17 16:09
Excelent, deploying to PROD

**Comment by ESapenaVentura** [comment] 2023-01-30 09:46
@Mil-m to test if this is reproducible (seems fixed)

**Comment by Mil-m** [comment] 2023-01-31 02:28
Everything looks fine

https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=4f9754c1-4b7c-4942-a031-7baf8bfcc696&project=dff56200-4091-48e8-8174-fe6a479be8da

**Comment by Mil-m** [comment] 2023-01-31 02:33
Everything looks fine

https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=4f9754c1-4b7c-4942-a031-7baf8bfcc696&project=dff56200-4091-48e8-8174-fe6a479be8da

**Comment by Mil-m** [comment] 2023-01-31 02:35
Everything looks fine

**Closed as completed** 2023-02-21 11:43 UTC
Labels: bug, FAIRification
