### ISSUE TITLE
FAIRness level dashboard

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#915] opened 2023-02-02 15:10 UTC

**Comment by Wkt8** [comment] 2023-02-03 14:17
![Screenshot 2023-02-01 at 14.43.35.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/ff19a404-49b9-41d3-91b6-f0b93d5e7686)

Action:
- [x] research FAIR dashboard of other places (FAIRplus) and find useful features https://fairplus-project.eu/impact/kpi-dashboard

**Comment by Wkt8** [comment] 2023-02-21 15:12
Researched and organised a meeting with Katherine, Lyndon and Tendayi - came away from the meeting with actions. 

Notes here: 
https://docs.google.com/document/d/1SGsPXggha3Q80c8VjMYpkHNxeZW8dM5Uxot3WNaacHQ/edit 

Outcomes:
eLwazi doesn't really need a FAIR dashboard yet because we don't have the necessary FAIR assessments and data. Focus on the eLwazi Catalogue, and reaching out to projects individually (after end of March meeting) where Lyndon will send out an email. 

Actions: 
- [ ] Reach out to FAIRplus and ask about their catalogue

**Comment by Wkt8** [comment] 2023-05-22 08:14
Decision on this postponed (see the 10.05.2023 meeting here https://docs.google.com/document/d/1XJIO5C4eelx1nU6LCFeF-9Z5Yivc0szsOF6Od9MPE98/edit#) until the value is confirmed. Closing.

**Closed as completed by Wkt8** 2023-05-22 08:14 UTC
Labels: FAIRification, eLwazi
